export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_FAIL ="GET_PRODUCT_FAIL"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_USER_PRODUCT_REQUEST ="GET_USER_PRODUCT_REQUEST";
export const GET_USER_PRODUCT_FAIL = "GET_USER_PRODUCT_FAIL";
export const GET_USER_PRODUCT_SUCCESS = "GET_USER_PRODUCT_SUCCESS";

export const GET_SINGLE_PRODUCT_FAIL ="GET_SINGLE_PRODUCT_FAIL";
export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";


export const CREATE_BID_FAIL ="CREATE_BID_FAIL";
export const CREATE_BID_REQUEST = "CREATE_BID_REQUEST";
export const CREATE_BID_SUCCESS = "CREATE_BID_SUCCESS";

export const GET_BID_FAIL ="GET_BID_FAIL";
export const GET_BID_REQUEST = "GET_BID_REQUEST";
export const GET_BID_SUCCESS = "GET_BID_SUCCESS";

export const REJECT_BID_FAIL ="REJECT_BID_FAIL";
export const REJECT_BID_SUCCESS = "REJECT_BID_SUCCESS";
export const REJECT_BID_REQUEST = "REJECT_BID_REQUEST";


export const EDIT_BID_FAIL ="EDIT_BID_FAIL";
export const EDIT_BID_SUCCESS = "EDIT_BID_SUCCESS";
export const EDIT_BID_REQUEST = "EDIT_BID_REQUEST";

export const ACCEPT_BID_FAIL ="ACCEPT_BID_FAIL";
export const ACCEPT_BID_SUCCESS = "ACCEPT_BID_SUCCESS";
export const ACCEPT_BID_REQUEST = "ACCEPT_BID_REQUEST ";

export const ADD_COMMENT_FAIL ="ADD_COMMENT_FAIL";
export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";


export const GET_COMMENT_FAIL ="GET_COMMENT_FAIL";
export const GET_COMMENT_REQUEST = "GET_COMMENT_REQUEST";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";


export const VERIFY_PRODUCT_REQUEST ="VERIFY_PRODUCT_REQUEST";
export const VERIFY_PRODUCT_FAIL = "VERIFY_PRODUCT_FAIL";
export const VERIFY_PRODUCT_SUCCESS = "VERIFY_PRODUCT_SUCCESS";


export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";


export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
