export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";

export const GET_USER_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const GET_USER_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const GET_USER_ORDER_FAIL = "PLACE_ORDER_FAIL";