export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_FAIL ="GET_PRODUCT_FAIL"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_USER_PRODUCT_REQUEST ="GET_USER_PRODUCT_REQUEST";
export const GET_USER_PRODUCT_FAIL = "GET_USER_PRODUCT_FAIL";
export const GET_USER_PRODUCT_SUCCESS = "GET_USER_PRODUCT_SUCCESS";

export const GET_SINGLE_PRODUCT_FAIL ="GET_SINGLE_PRODUCT_FAIL";
export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";

