export const GET_RECYCLER_REQUEST = "GET_RECYCLER_REQUEST";
export const GET_RECYCLER_SUCCESS = "GET_RECYCLER_SUCCESS";
export const GET_RECYCLER_FAIL = "GET_RECYCLER_FAIL";

export const CREATE_RECYCLER_REQUEST = "CREATE_RECYCLER_REQUEST";
export const CREATE_RECYCLER_SUCCESS = "CREATE_RECYCLER_SUCCESS";
export const CREATE_RECYCLER_FAIL = "CREATE_RECYCLER_FAIL";

export const DELETE_RECYCLER_REQUEST = "DELETE_RECYCLER_REQUEST";
export const DELETE_RECYCLER_SUCCESS = "DELETE_RECYCLER_SUCCESS";
export const DELETE_RECYCLER_FAIL = "DELETE_RECYCLER_FAIL";


export const GET_SINGLE_RECYCLER_REQUEST = "GET_SINGLE_RECYCLER_REQUEST";
export const GET_SINGLE_RECYCLER_SUCCESS = "GET_SINGLE_RECYCLER_SUCCESS";
export const GET_SINGLE_RECYCLER_FAIL = "GET_SINGLE_RECYCLER_FAIL";