export const GET_RECYCLER_REQUEST = "GET_RECYCLER_REQUEST";
export const GET_RECYCLER_SUCCESS = "GET_RECYCLER_SUCCESS";
export const GET_RECYCLER_FAIL = "GET_RECYCLER_FAIL";

export const CREATE_RECYCLER_REQUEST = "GET_RECYCLER_REQUEST";
export const CREATE_RECYCLER_SUCCESS = "GET_RECYCLER_SUCCESS";
export const CREATE_RECYCLER_FAIL = "GET_RECYCLER_FAIL";